name: Multi-Platform Docker Build

on:
  push:
    tags: ['image-*']
  workflow_dispatch:    # keep this to allow manual triggering of the workflow

jobs:
  build-multi-arch:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write  # multipass needs this permission to authenticate with the registry

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          platforms: linux/amd64,linux/arm64,linux/arm/v7  # set the platforms you want to build for

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Multi-Arch Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/allin1-ubuntu.Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: |
            ghcr.io/crossoverjie/allin1-ubuntu:latest
            ghcr.io/crossoverjie/allin1-ubuntu:${{ github.run_id }}
          cache-from: type=gha
          cache-to: type=gha,mode=max